-
  name: this is 1st play
  hosts: webserver1
  vars:
    age: 11
  tasks:
    -
      name: "creating file using variable"
      command: touch /tmp/check_OR.txt
      when: age == 10 or age == 11

