-
  name: this is our first play
  hosts: webserver1
  tasks:
    -
      name: "Create a dummy file on webserver1"
      command: touch /tmp/ansible_dummy.txt
    -
      name: "Create folder on server"
      command: mkdir /tmp/myfolder
