-
  name: this is our first play
  hosts: webserver1
  tasks:
    -
      name: "Create a dummy file on webserver1"
      command: touch /tmp/ansible_dummy.txt
    -
      name: "Create folder on server"
      command: mkdir /tmp/myfolder

-
  name: this is 2nd play
  hosts: webserver1
  tasks:
    -
      name: "Create the backup directory under tmp directory"
      command: mkdir /tmp/backup
    -
      name: "copy the password file in backup directory"
      command: cp /etc/passwd /tmp/backup

